apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscaling-deploy
  namespace: default
  labels:
    app: autoscaling
    release: prom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoscaling
      release: prom
  template:
    metadata:
      labels:
        app: autoscaling
        release: prom
    spec:
      containers:
        - name: autoscaling
          image: quay.io/brancz/prometheus-example-app:v0.1.0
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: autoscaling-service
  namespace: default
  labels:
    release: prom
    app: autoscaling
spec:
  ports:
    - name: metrics-svc-port
      port: 80
      targetPort: 8080
  selector:
    app: autoscaling
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: autoscaling-sm
  namespace: prometheus
  labels:
    serviceMonitorSelector: prometheus
spec:
  selector:
    matchLabels:
      release: prom
      app: autoscaling
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics-svc-port
      interval: 10s
      path: /metrics
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: autoscaling-app-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: autoscaling-deploy
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Pods
      pods:
        metric:
          name: http_requests
        target:
          type: AverageValue
          averageValue: 5m
