apiVersion: apps/v1
kind: Deployment
metadata:
  name: focalboard-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: focalboard
  template:
    metadata:
      labels:
        app: focalboard
    spec:
      containers:
        - name: focalboard
          image: mattermost/focalboard
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: focalboard-service
spec:
  selector:
    app: focalboard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
