apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-two
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: app-two
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-two
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - app-one
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: app-two-container
          image: nginx:latest
