apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-three
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: app-three
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-three
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app.kubernetes.io/name"
                    operator: In
                    values:
                      - app-one
                      - app-two
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: app-three-container
          image: nginx:latest
